services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3000"  # Changed from 3001:3000
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@db:5432/gamehub
      - BACKEND_URL=http://backend:8002  # Updated backend URL
    depends_on:
      - backend
    networks:
      - gamehub-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8001"  # Changed from 8001:8001
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@db:5432/gamehub
      - PORT=8001
    depends_on:
      - db
    networks:
      - gamehub-network
    command: ["node", "server.js"]

  db:
    image: postgres:16
    ports:
      - "5435:5432"  # Changed from 5434 to 5435
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gamehub
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - gamehub-network

volumes:
  postgres_data:

networks:
  gamehub-network:
    driver: bridge